//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Gusker;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ArticlesSection.CLASS_NAME, typeof(ArticlesSection))]

namespace CMS.DocumentEngine.Types.Gusker
{
	/// <summary>
	/// Represents a content item of type ArticlesSection.
	/// </summary>
	public partial class ArticlesSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Gusker.ArticlesSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with ArticlesSection fields.
		/// </summary>
		private readonly ArticlesSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ArticlesSectionID.
		/// </summary>
		[DatabaseIDField]
		public int ArticlesSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ArticlesSectionID"), 0);
			}
			set
			{
				SetValue("ArticlesSectionID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ArticlesSection fields.
		/// </summary>
		[RegisterProperty]
		public ArticlesSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ArticlesSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ArticlesSectionFields : AbstractHierarchicalObject<ArticlesSectionFields>
		{
			/// <summary>
			/// The content item of type ArticlesSection that is a target of the extended API.
			/// </summary>
			private readonly ArticlesSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ArticlesSectionFields" /> class with the specified content item of type ArticlesSection.
			/// </summary>
			/// <param name="instance">The content item of type ArticlesSection that is a target of the extended API.</param>
			public ArticlesSectionFields(ArticlesSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ArticlesSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ArticlesSectionID;
				}
				set
				{
					mInstance.ArticlesSectionID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ArticlesSection" /> class.
		/// </summary>
		public ArticlesSection() : base(CLASS_NAME)
		{
			mFields = new ArticlesSectionFields(this);
		}

		#endregion
	}
}