//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Gusker;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ContactsSection.CLASS_NAME, typeof(ContactsSection))]

namespace CMS.DocumentEngine.Types.Gusker
{
	/// <summary>
	/// Represents a content item of type ContactsSection.
	/// </summary>
	public partial class ContactsSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Gusker.ContactsSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactsSection fields.
		/// </summary>
		private readonly ContactsSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ContactsSectionID.
		/// </summary>
		[DatabaseIDField]
		public int ContactsSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ContactsSectionID"), 0);
			}
			set
			{
				SetValue("ContactsSectionID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactsSection fields.
		/// </summary>
		[RegisterProperty]
		public ContactsSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactsSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactsSectionFields : AbstractHierarchicalObject<ContactsSectionFields>
		{
			/// <summary>
			/// The content item of type ContactsSection that is a target of the extended API.
			/// </summary>
			private readonly ContactsSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactsSectionFields" /> class with the specified content item of type ContactsSection.
			/// </summary>
			/// <param name="instance">The content item of type ContactsSection that is a target of the extended API.</param>
			public ContactsSectionFields(ContactsSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ContactsSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ContactsSectionID;
				}
				set
				{
					mInstance.ContactsSectionID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactsSection" /> class.
		/// </summary>
		public ContactsSection() : base(CLASS_NAME)
		{
			mFields = new ContactsSectionFields(this);
		}

		#endregion
	}
}