//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Gusker;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(NavigationContainer.CLASS_NAME, typeof(NavigationContainer))]

namespace CMS.DocumentEngine.Types.Gusker
{
	/// <summary>
	/// Represents a content item of type NavigationContainer.
	/// </summary>
	public partial class NavigationContainer : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Gusker.NavigationContainer";


		/// <summary>
		/// The instance of the class that provides extended API for working with NavigationContainer fields.
		/// </summary>
		private readonly NavigationContainerFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// NavigationContainerID.
		/// </summary>
		[DatabaseIDField]
		public int NavigationContainerID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("NavigationContainerID"), 0);
			}
			set
			{
				SetValue("NavigationContainerID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with NavigationContainer fields.
		/// </summary>
		[RegisterProperty]
		public NavigationContainerFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with NavigationContainer fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class NavigationContainerFields : AbstractHierarchicalObject<NavigationContainerFields>
		{
			/// <summary>
			/// The content item of type NavigationContainer that is a target of the extended API.
			/// </summary>
			private readonly NavigationContainer mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="NavigationContainerFields" /> class with the specified content item of type NavigationContainer.
			/// </summary>
			/// <param name="instance">The content item of type NavigationContainer that is a target of the extended API.</param>
			public NavigationContainerFields(NavigationContainer instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// NavigationContainerID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.NavigationContainerID;
				}
				set
				{
					mInstance.NavigationContainerID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="NavigationContainer" /> class.
		/// </summary>
		public NavigationContainer() : base(CLASS_NAME)
		{
			mFields = new NavigationContainerFields(this);
		}

		#endregion
	}
}